<?php

use Illuminate\Database\Seeder;
use App\Rango;

class CostosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('costos')->insert([
            [
                'porcentaje'      => '0',
                'ene-feb'         => '$1,514',
                'mar-abr'         => '$1,462',
                'may-jun'         => '$2,274',
                'jul-ago'         => '$2,248',
                'sep-oct'         => '$2,222',
                'nov-dic'         => '$1,489',
                'anual'           => '$11,210',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '1',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '100',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$321',
                'jul-ago'         => '$314',
                'sep-oct'         => '$306',
                'nov-dic'         => '$0',
                'anual'           => '$403',
                'paneles'         => '16',
                'rango_inversion' => '$159,161',
                'rango_id'        => '1',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '80',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$481',
                'jul-ago'         => '$471',
                'sep-oct'         => '$462',
                'nov-dic'         => '$0',
                'anual'           => '$1,414',
                'paneles'         => '13',
                'rango_inversion' => '$111,924',
                'rango_id'        => '1',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '60',
                'ene-feb'         => '$125',
                'mar-abr'         => '$109',
                'may-jun'         => '$678',
                'jul-ago'         => '$668',
                'sep-oct'         => '$658',
                'nov-dic'         => '$116',
                'anual'           => '$2,354',
                'paneles'         => '10',
                'rango_inversion' => '$101,452',
                'rango_id'        => '1',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '40',
                'ene-feb'         => '$466',
                'mar-abr'         => '$414',
                'may-jun'         => '$1,226',
                'jul-ago'         => '$1,200',
                'sep-oct'         => '$1,174',
                'nov-dic'         => '$440',
                'anual'           => '$4,920',
                'paneles'         => '6',
                'rango_inversion' => '$67,127',
                'rango_id'        => '1',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '0',
                'ene-feb'         => '$2,905',
                'mar-abr'         => '$2,820',
                'may-jun'         => '$4,836',
                'jul-ago'         => '$4,793',
                'sep-oct'         => '$4,751',
                'nov-dic'         => '$2,863',
                'anual'           => '$22,970',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '2',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '100',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$521',
                'jul-ago'         => '$505',
                'sep-oct'         => '$499',
                'nov-dic'         => '$0',
                'anual'           => '$1,525',
                'paneles'         => '24',
                'rango_inversion' => '$223,505',
                'rango_id'        => '2',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '80',
                'ene-feb'         => '$73',
                'mar-abr'         => '$49',
                'may-jun'         => '$1,517',
                'jul-ago'         => '$1,474',
                'sep-oct'         => '$1,432',
                'nov-dic'         => '$61',
                'anual'           => '$4,604',
                'paneles'         => '19',
                'rango_inversion' => '$158,751',
                'rango_id'        => '2',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '60',
                'ene-feb'         => '$459',
                'mar-abr'         => '$374',
                'may-jun'         => '$2,390',
                'jul-ago'         => '$2,347',
                'sep-oct'         => '$2,305',
                'nov-dic'         => '$417',
                'anual'           => '$8,293',
                'paneles'         => '15',
                'rango_inversion' => '$137,208',
                'rango_id'        => '2',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '40',
                'ene-feb'         => '$1,333',
                'mar-abr'         => '$1,248',
                'may-jun'         => '$3,264',
                'jul-ago'         => '$3,221',
                'sep-oct'         => '$3,179',
                'nov-dic'         => '$1,291',
                'anual'           => '$13,535',
                'paneles'         => '10',
                'rango_inversion' => '$101,452',
                'rango_id'        => '2',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '0',
                'ene-feb'         => '$6,442',
                'mar-abr'         => '$6,480',
                'may-jun'         => '$7,200',
                'jul-ago'         => '$7,277',
                'sep-oct'         => '$7,238',
                'nov-dic'         => '$6,403',
                'anual'           => '$41,040',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '3',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '100',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$461',
                'jul-ago'         => '$537',
                'sep-oct'         => '$499',
                'nov-dic'         => '$0',
                'anual'           => '$605',
                'paneles'         => '30',
                'rango_inversion' => '$253,066',
                'rango_id'        => '3',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '80',
                'ene-feb'         => '$826',
                'mar-abr'         => '$864',
                'may-jun'         => '$1,584',
                'jul-ago'         => '$1,661',
                'sep-oct'         => '$1,622',
                'nov-dic'         => '$787',
                'anual'           => '$7,344',
                'paneles'         => '22',
                'rango_inversion' => '$179,854',
                'rango_id'        => '3',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '60',
                'ene-feb'         => '$2,398',
                'mar-abr'         => '$2,436',
                'may-jun'         => '$3,156',
                'jul-ago'         => '$3,233',
                'sep-oct'         => '$3,195',
                'nov-dic'         => '$2,360',
                'anual'           => '$16,779',
                'paneles'         => '15',
                'rango_inversion' => '$137,208',
                'rango_id'        => '3',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '40',
                'ene-feb'         => '$3,746',
                'mar-abr'         => '$3,784',
                'may-jun'         => '$4,504',
                'jul-ago'         => '$4,581',
                'sep-oct'         => '$4,542',
                'nov-dic'         => '$3,708',
                'anual'           => '$24,866',
                'paneles'         => '8',
                'rango_inversion' => '$86,578',
                'rango_id'        => '3',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '0',
                'ene-feb'         => '$8,476',
                'mar-abr'         => '$8,526',
                'may-jun'         => '$9,474',
                'jul-ago'         => '$9,574',
                'sep-oct'         => '$9,524',
                'nov-dic'         => '$8,426',
                'anual'           => '$54,000',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '4',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '100',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$937',
                'jul-ago'         => '$1,038',
                'sep-oct'         => '$987',
                'nov-dic'         => '$0',
                'anual'           => '$2,782',
                'paneles'         => '36',
                'rango_inversion' => '$296,843',
                'rango_id'        => '4',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '80',
                'ene-feb'         => '$1,288',
                'mar-abr'         => '$1,338',
                'may-jun'         => '$2,285',
                'jul-ago'         => '$2,386',
                'sep-oct'         => '$2,335',
                'nov-dic'         => '$1,237',
                'anual'           => '$10,869',
                'paneles'         => '30',
                'rango_inversion' => '$293,557',
                'rango_id'        => '4',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '60',
                'ene-feb'         => '$2,860',
                'mar-abr'         => '$2,910',
                'may-jun'         => '$3,858',
                'jul-ago'         => '$3,958',
                'sep-oct'         => '$3,908',
                'nov-dic'         => '$2,810',
                'anual'           => '$20,304',
                'paneles'         => '25',
                'rango_inversion' => '$229,505',
                'rango_id'        => '4',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '40',
                'ene-feb'         => '$4,882',
                'mar-abr'         => '$4,932',
                'may-jun'         => '$5,879',
                'jul-ago'         => '$5,980',
                'sep-oct'         => '$5,930',
                'nov-dic'         => '$4,831',
                'anual'           => '$32,435',
                'paneles'         => '16',
                'rango_inversion' => '$145,208',
                'rango_id'        => '4',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '0',
                'ene-feb'         => '$10,171',
                'mar-abr'         => '$10,232',
                'may-jun'         => '$11,368',
                'jul-ago'         => '$11,489',
                'sep-oct'         => '$11,429',
                'nov-dic'         => '$10,111',
                'anual'           => '$64,800',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '5',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '100',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$586',
                'jul-ago'         => '$707',
                'sep-oct'         => '$646',
                'nov-dic'         => '$0',
                'anual'           => '$1,938',
                'paneles'         => '41',
                'rango_inversion' => '$385,862',
                'rango_id'        => '5',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '80',
                'ene-feb'         => '$1,635',
                'mar-abr'         => '$1,695',
                'may-jun'         => '$2,832',
                'jul-ago'         => '$2,953',
                'sep-oct'         => '$2,892',
                'nov-dic'         => '$1,574',
                'anual'           => '$13,582',
                'paneles'         => '33',
                'rango_inversion' => '$315,867',
                'rango_id'        => '5',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '60',
                'ene-feb'         => '$3,432',
                'mar-abr'         => '$3,492',
                'may-jun'         => '$4,629',
                'jul-ago'         => '$4,750',
                'sep-oct'         => '$4,689',
                'nov-dic'         => '$3,371',
                'anual'           => '$24,365',
                'paneles'         => '24',
                'rango_inversion' => '$223,505',
                'rango_id'        => '5',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '40',
                'ene-feb'         => '$5,679',
                'mar-abr'         => '$5,739',
                'may-jun'         => '$6,876',
                'jul-ago'         => '$6,997',
                'sep-oct'         => '$6,936',
                'nov-dic'         => '$5,618',
                'anual'           => '$37,843',
                'paneles'         => '16',
                'rango_inversion' => '$145,208',
                'rango_id'        => '5',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
        	[
                'porcentaje'      => '0',
                'ene-feb'         => '$8,476',
                'mar-abr'         => '$8,526',
                'may-jun'         => '$9,474',
                'jul-ago'         => '$9,574',
                'sep-oct'         => '$9,524',
                'nov-dic'         => '$8,426',
                'anual'           => '$54,000',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '6',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '0',
                'ene-feb'         => '$12,206',
                'mar-abr'         => '$12,278',
                'may-jun'         => '$13,642',
                'jul-ago'         => '$13,787',
                'sep-oct'         => '$13,714',
                'nov-dic'         => '$12,133',
                'anual'           => '$77,760',
                'paneles'         => '0',
                'rango_inversion' => '$0',
                'rango_id'        => '6',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '100',
                'ene-feb'         => '$0',
                'mar-abr'         => '$0',
                'may-jun'         => '$1,287',
                'jul-ago'         => '$1,432',
                'sep-oct'         => '$1,359',
                'nov-dic'         => '$0',
                'anual'           => '$4,078',
                'paneles'         => '48',
                'rango_inversion' => '$406,276',
                'rango_id'        => '6',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '80',
                'ene-feb'         => '$2,097',
                'mar-abr'         => '$2,169',
                'may-jun'         => '$3,533',
                'jul-ago'         => '$3,678',
                'sep-oct'         => '$3,605',
                'nov-dic'         => '$2,024',
                'anual'           => '$17,107',
                'paneles'         => '38',
                'rango_inversion' => '$319,817',
                'rango_id'        => '6',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'porcentaje'      => '60',
                'ene-feb'         => '$4,343',
                'mar-abr'         => '$4,415',
                'may-jun'         => '$5,780',
                'jul-ago'         => '$5,925',
                'sep-oct'         => '$5,852',
                'nov-dic'         => '$4,270',
                'anual'           => '$30,586',
                'paneles'         => '29',
                'rango_inversion' => '$286,120',
                'rango_id'        => '6',
                'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
            ],
        	[
            	'porcentaje'      => '40',
        		'ene-feb'	      => '$6,814',
        		'mar-abr'	      => '$6,887',
        		'may-jun'	      => '$8,251',
        		'jul-ago'	      => '$8,396',
        		'sep-oct'	      => '$8,323',
        		'nov-dic'	      => '$6,741',
        		'anual'		      => '$45,412',
                'paneles'         => '19',
        		'rango_inversion' => '$158,751',
        		'rango_id'	      => '6',
        		'created_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        		'updated_at'      => \Carbon\Carbon::now()->format('Y-m-d H:i:s')
        	]
        ]);
    }
}
